engines:
  duplication:
    enabled: true
    config:
      languages:
        -javascript
  eslint: 
    enabled: true
    checks:
      similar-code:
        enabled: true
exclude_sparherns:
- "node_modules/"
- ".nyc_output"
- "coverage"
- "./tests/*.js"
- "UI"